import Layout from '@/components/layout/Layout';
import SEO from '@/components/layout/SEO';
import ProductGrid from '@/components/commerce/ProductGrid';
import Button from '@/components/ui/Button';
import { PRODUCTS } from '@/data/products';
import { canonical } from '@/lib/seo';

export default function HomePage() {
  return <Layout headerVariant='home'><SEO title='MB BRANDNAME — No.1 Luxury Store' description='Discover MB BRANDNAME. Luxury bags, accessories, and new arrivals.' canonical={canonical('/')} /><main><section className='relative h-screen'><div className='container mx-auto px-4 h-full'><div className='absolute inset-0 grid h-full w-full grid-cols-12 grid-rows-6'><div className='col-span-7 row-span-6'><img src='/assets/mb/v1/hero1.svg' alt='hero' className='h-full w-full object-cover' /></div><div className='col-span-5 row-span-3'><img src='/assets/mb/v1/hero2.svg' alt='hero' className='h-full w-full object-cover' /></div><div className='col-span-5 row-span-3'><img src='/assets/mb/v1/hero3.svg' alt='hero' className='h-full w-full object-cover' /></div></div><div className='absolute inset-0 bg-black/25'/><div className='absolute inset-0 flex items-center justify-center px-6'><h1 className='text-center text-[30px] lg:text-[52px] font-light tracking-[0.06em] text-white leading-[1.08]'>NO.1 MB BRANDNAME STORE</h1></div><div className='absolute bottom-10 left-1/2 -translate-x-1/2 flex gap-2.5'><span className='h-2 w-2 rounded-full bg-white'/><span className='h-2 w-2 rounded-full bg-white/50'/><span className='h-2 w-2 rounded-full bg-white/50'/></div></div></section><section className='bg-[var(--bg-alt)] py-14 lg:py-20'><div className='container mx-auto px-4'><h2 className='mb-10 text-center text-[18px] lg:text-[20px] leading-[1.2] tracking-[0.22em] font-medium uppercase'>New Arrivals</h2><ProductGrid products={PRODUCTS} /><div className='mt-10 text-center'><Button href='/new-arrivals'>View more</Button></div></div></section><section className='py-14 lg:py-20'><div className='container mx-auto px-4 grid grid-cols-1 gap-10 lg:grid-cols-2'><img src='/assets/mb/v1/hero1.svg' alt='story' className='w-full shadow-[0_8px_30px_rgba(0,0,0,0.08)]'/><div><h2 className='text-[18px] lg:text-[20px] uppercase tracking-[0.22em] mb-6'>Our Story</h2><p className='text-[14px] lg:text-[15px] leading-[1.7] text-[var(--muted)]'>We curate authenticated secondhand luxury pieces with strict quality standards.</p></div></div></section><section className='py-14 lg:py-20'><div className='container mx-auto px-4'><h2 className='text-[18px] lg:text-[20px] uppercase tracking-[0.22em] mb-6'>Guarantee</h2><p className='text-[14px] lg:text-[15px] leading-[1.7] text-[var(--muted)]'>100% AUTHENTIC BRANDED ITEMS FROM JAPAN WITH OVER 10 YEARS OF EXPERIENCE IN AUTHENTIC SECONDHAND BRANDED GOODS, WE GUARANTEE GENUINE QUALITY.</p></div></section><section className='py-14 lg:py-20'><div className='container mx-auto px-4 grid grid-cols-1 gap-8 md:grid-cols-3'><div>Free Shipping</div><div>Authenticity Guarantee</div><div>Secure Checkout</div></div></section></main></Layout>;
}
